services:
  pocketbase:
    build: ./pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src

volumes:
  pb_data:
